---
title: "Statistical Learning"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(11)
library(tidyverse)
library(glmnet)
```

## Lasso

Predicting birthweight

```{r lasso}
bwt_df = 
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)
```

## let's do lasso

```{r , echo=FALSE}
y = bwt_df %>% pull(bwt)
x = model.matrix(bwt ~ ., bwt_df)[,-1]
```

Let's fit lasso

```{r}
lambda_grid = 10 ^ seq(3, -2, by = -0.1)

lasso_fit = glmnet(x, y, lambda = lambda_grid)

lasso_fit

## cv
lasso_cv = cv.glmnet(x, y, lambda = lambda_grid)
lasso_opt = lasso_cv$lambda.min
```

See what we actually did

```{r}
lasso_fit %>%
  broom::tidy() %>%
  complete(term, lambda, fill = list(estimate = 0)) %>%
  filter(term != '(Intercept)') %>%
  ggplot(aes(x = log(lambda), y = estimate, group = term, color = term)) + 
  geom_path() + 
  geom_vline(xintercept = log(lasso_opt, 10), color = "blue", size = 1.2) #+
  #theme(legend.position = "none")
```

## Cluster pokemon
```{r}
pokemon_df = 
  read_csv("data/pokemon.csv") %>%
  janitor::clean_names() %>%
  select(speed, hp)
```

Take a quick look at our pokemon

```{r}
pokemon_df %>% 
  ggplot(aes(x = hp, y = speed)) + 
  geom_point()
```

```{r}
kmeans_fit = 
  kmeans(x = pokemon_df, centers = 3)
```

```{r}
pokemon_df %>%
  broom::augment(kmeans_fit, .) %>%
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()
```

## Trajectory

```{r}
traj_data = 
  read_csv("./data/trajectories.csv")
```


